#!/bin/bash

PING_TARGET="8.8.8.8"
PING_COUNT="3"
LOG_FILE="/dev/shm/record"
QMI_NODE="/dev/cdc-wdm0"
#QMI_IF="wwan0"
#PIN_CODE="0000"

# to keep wifi connection alive.
keep_alive () {
	local err_cnt=0
	ping $PING_TARGET -c $PING_COUNT
	while [ x"$?" != x"0" ]; 
	do
		err_cnt=$(($err_cnt+1))
		wifi_mgmt restart
		sleep 10
		# ifconfig ${QMI_IF} mtu 1500
		date=$(date +"%Y/%m/%d %H:%M:%S")
		echo "$date Cannot ping $PING_TARGET, restart the connection..." > $LOG_FILE
		ping $PING_TARGET -c $PING_COUNT
	done
}

count=0

while true; do
	# keep alive every 5 min.
	if [ x"$(($count%5))" == x"0" ]; then
		keep_alive
	fi
	# log data in every 10-min.
	if [ x"$(($count%10))" == x"0" ]; then
		count=0
	fi
	count=$(($count+1))
	sleep 59
done
